repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: debug-statements

- repo: local
  hooks:
  # --- TYPESCRIPT HOOKS ---
  - id: ts-format
    name: format (ts-sdk)
    entry: bash -c 'cd ts-sdk && npm run format'
    language: system
    pass_filenames: false
    files: ^ts-sdk/

  - id: ts-lint
    name: lint (ts-sdk)
    entry: bash -c 'cd ts-sdk && npm run lint:fix'
    language: system
    pass_filenames: false
    files: ^ts-sdk/

  - id: ts-typecheck
    name: typecheck (ts-sdk)
    entry: bash -c 'cd ts-sdk && npm run typecheck'
    language: system
    pass_filenames: false
    files: ^ts-sdk/

  - id: ts-test
    name: test (ts-sdk)
    entry: bash -c 'cd ts-sdk && npm run test'
    language: system
    pass_filenames: false
    files: ^ts-sdk/