import type { CallContext } from './context.js';

/** Represents the author of a message in the conversation. */
export type Role = 'system' | 'user' | 'assistant' | 'tool';

/** A single normalized message within an LLM conversation. */
export interface Message {
  role: Role;
  content: string;
}

/**
 * A provider-agnostic representation of an LLM request.
 * Passed to 'before' hooks.
 */
export interface LLMRequest {
  /** The list of messages in the conversation. */
  messages: Message[];
  /** The model identifier (e.g., 'gpt-4'). */
  model?: string;
  /** Additional provider-specific parameters (temperature, max_tokens, etc.). */
  params?: Record<string, unknown>;
  /** Arbitrary metadata attached to the request. */
  metadata?: Record<string, unknown>;
}

/**
 * Standardized token usage statistics for an LLM response.
 */
export interface Usage {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
}

/**
 * A provider-agnostic representation of an LLM response.
 * Passed to 'after' hooks.
 */
export interface LLMResponse {
  /** The text content generated by the model. */
  content: string;
  /** Token usage statistics. */
  usage?: Usage;
  /** The original, provider-specific response object (e.g., OpenAI response body). */
  raw?: unknown;
  /** Arbitrary metadata attached to the response. */
  metadata?: Record<string, unknown>;
}

/**
 * Interface for objects that can handle a direct Axon call.
 */
export interface LLMAdapter {
  call: (request: LLMRequest, ctx: CallContext) => LLMResponse | Promise<LLMResponse>;
}

/**
 * Hook function executed before an LLM call.
 * * @returns A modified request object, or `undefined`/`void` to leave the request unmodified.
 */
export type BeforeHook = (
  req: LLMRequest,
  ctx: CallContext
) => LLMRequest | Promise<LLMRequest> | Promise<undefined> | Promise<void> | undefined;

/**
 * Hook function executed after an LLM call.
 * * @returns A modified response object, or `undefined`/`void` to leave the response unmodified.
 */
export type AfterHook = (
  req: LLMRequest,
  res: LLMResponse,
  ctx: CallContext
) => LLMResponse | Promise<LLMResponse> | Promise<undefined> | Promise<void> | undefined;
